name: Deployment
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: CDN Deployment
        uses: nebula-dev/spaces-sync-action@master
        env:
          SOURCE_DIR: './static/'
          SPACE_REGION: 'sfo2'
          SPACE_NAME: ${{ secrets.SPACE_NAME }}
          SPACE_ACCESS_KEY: ${{ secrets.SPACE_ACCESS_KEY }}
          SPACE_SECRET_KEY: ${{ secrets.SPACE_SECRET_KEY }}

      - name: CDN Linking
        uses: nebula-dev/cdn-linking-action@master
        env:
          TARGET_SRC: 'static/'
          CDN_BASE_URL: 'https://static.nebula.dev/'
          CDN_PATH: 'nebula-web/'

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: deploy # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          PRESERVE: true
          CLEAN: true # Automatically remove deleted files from the deploy branch
      
      - name: Report Generation
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          urls: ''

