name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: CDN Linking
        uses: nebula-dev/cdn-linking-action@master
        env:
          TARGET_SRC: 'static/'
          CDN_BASE_URL: 'https://static.nebula.dev/'
          CDN_PATH: 'nebula-web/'

      - name: rsync Bundle
        uses: up9cloud/action-rsync@v1.3
        env:
          MODE: local
          SOURCE: ./
          TARGET: ./bundle/
          ARGS: -av --exclude=".*"
          PRE_SCRIPT: |
            mkdir ./bundle/

      - name: GCP Setup
        uses: google-github-actions/setup-gcloud@master
        with: 
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SERVICE_EMAIL }}
          service_account_key: ${{ secrets.GCP_SERVICE_PK }}
          export_default_credentials: true

      - name: GCP Storage Upload
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ./bundle/
          destination: nebula-web


      
      

