name: Static Linking
on:
  push:
    branches: [ master ]
jobs:
  link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: CDN Linking
        uses: nebula-dev/cdn-linking-action@master
        env:
          TARGET_SRC: 'static/'
          CDN_BASE_URL: 'https://static.nebula.dev/'
          CDN_PATH: 'nebula-web/'

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: deploy # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          PRESERVE: true
          CLEAN: true # Automatically remove deleted files from the deploy branch
      
      

